# SmogPing Example Targets Configuration
# This file contains example targets for common network monitoring scenarios
# Copy this to targets.toml and customize for your environment

# Include additional target files (optional)
# include = ["additional_targets.toml", "datacenter_hosts.toml"]

[organizations]

  # Public DNS Servers - Essential for internet connectivity monitoring
  [organizations.DNS]
  hosts = [
    # Google DNS
    { name = "Google DNS Primary", ip = "8.8.8.8", alarmping = 100, alarmloss = 2, alarmjitter = 50 },
    { name = "Google DNS Secondary", ip = "8.8.4.4", alarmping = 100, alarmloss = 2, alarmjitter = 50 },
    
    # Cloudflare DNS
    { name = "Cloudflare DNS Primary", ip = "1.1.1.1", alarmping = 100, alarmloss = 2, alarmjitter = 50 },
    { name = "Cloudflare DNS Secondary", ip = "1.0.0.1", alarmping = 100, alarmloss = 2, alarmjitter = 50 },
    
    # Quad9 DNS
    { name = "Quad9 DNS Primary", ip = "9.9.9.9", alarmping = 100, alarmloss = 2, alarmjitter = 50 },
    { name = "Quad9 DNS Secondary", ip = "149.112.112.112", alarmping = 100, alarmloss = 2, alarmjitter = 50 },
    
    # OpenDNS
    { name = "OpenDNS Primary", ip = "208.67.222.222", alarmping = 150, alarmloss = 3, alarmjitter = 75 },
    { name = "OpenDNS Secondary", ip = "208.67.220.220", alarmping = 150, alarmloss = 3, alarmjitter = 75 }
  ]

  # Major Website Endpoints - Monitor popular services
  [organizations.Websites]
  hosts = [
    # Search Engines
    { name = "Google", ip = "google.com", alarmping = 100, alarmloss = 2, alarmjitter = 50 },
    { name = "Bing", ip = "bing.com", alarmping = 150, alarmloss = 3, alarmjitter = 75 },
    { name = "DuckDuckGo", ip = "duckduckgo.com", alarmping = 200, alarmloss = 5, alarmjitter = 100 },
    
    # Social Media
    { name = "Facebook", ip = "facebook.com", alarmping = 200, alarmloss = 5, alarmjitter = 100 },
    { name = "X Twitter", ip = "x.com", alarmping = 200, alarmloss = 5, alarmjitter = 100 },
    { name = "LinkedIn", ip = "linkedin.com", alarmping = 250, alarmloss = 5, alarmjitter = 125 },
    
    # Tech Companies
    { name = "GitHub", ip = "github.com", alarmping = 200, alarmloss = 5, alarmjitter = 100 },
    { name = "Stack Overflow", ip = "stackoverflow.com", alarmping = 250, alarmloss = 5, alarmjitter = 125 },
    { name = "Reddit", ip = "reddit.com", alarmping = 300, alarmloss = 10, alarmjitter = 150 }
  ]

  # Geographic Diversity - Test connectivity to different regions
  [organizations.Geographic]
  hosts = [
    # North America
    { name = "Level3 Chicago", ip = "4.2.2.1", alarmping = 150, alarmloss = 3, alarmjitter = 75 },
    { name = "Level3 Denver", ip = "4.2.2.2", alarmping = 200, alarmloss = 5, alarmjitter = 100 },
    
    # Europe
    { name = "Level3 London", ip = "4.2.2.3", alarmping = 300, alarmloss = 5, alarmjitter = 150 },
    { name = "Level3 Frankfurt", ip = "4.2.2.4", alarmping = 350, alarmloss = 5, alarmjitter = 175 },
    
    # Asia Pacific
    { name = "Level3 Tokyo", ip = "4.2.2.5", alarmping = 400, alarmloss = 10, alarmjitter = 200 },
    { name = "Level3 Singapore", ip = "4.2.2.6", alarmping = 450, alarmloss = 10, alarmjitter = 225 }
  ]

  # ISP and Tier 1 Providers
  [organizations.ISP]
  hosts = [
    # Tier 1 Providers
    { name = "Verizon Business", ip = "4.69.202.123", alarmping = 150, alarmloss = 3, alarmjitter = 75 },
    { name = "ATT", ip = "12.0.1.1", alarmping = 150, alarmloss = 3, alarmjitter = 75 },
    { name = "Level3 CenturyLink", ip = "4.2.2.1", alarmping = 150, alarmloss = 3, alarmjitter = 75 },
    { name = "NTT Communications", ip = "129.250.35.250", alarmping = 200, alarmloss = 5, alarmjitter = 100 },
    { name = "Cogent", ip = "38.104.1.1", alarmping = 150, alarmloss = 3, alarmjitter = 75 },
    
    # Major US Consumer ISPs
    { name = "Comcast", ip = "68.87.64.146", alarmping = 150, alarmloss = 3, alarmjitter = 75 },
    { name = "Charter Spectrum", ip = "209.18.47.61", alarmping = 150, alarmloss = 3, alarmjitter = 75 },
    { name = "Cox Communications", ip = "68.230.200.12", alarmping = 150, alarmloss = 3, alarmjitter = 75 },
    { name = "Altice USA", ip = "167.206.6.6", alarmping = 150, alarmloss = 3, alarmjitter = 75 },
    
    # Canadian ISPs
    { name = "Rogers Canada", ip = "64.71.255.204", alarmping = 200, alarmloss = 5, alarmjitter = 100 },
    { name = "Bell Canada", ip = "64.230.128.1", alarmping = 200, alarmloss = 5, alarmjitter = 100 },
    { name = "Telus", ip = "154.11.255.204", alarmping = 200, alarmloss = 5, alarmjitter = 100 },
    { name = "Shaw Canada", ip = "64.59.144.22", alarmping = 200, alarmloss = 5, alarmjitter = 100 },
    
    # Major Regional/Enterprise ISPs
    { name = "Hurricane Electric", ip = "74.82.42.42", alarmping = 150, alarmloss = 3, alarmjitter = 75 },
    { name = "GTT Tinet", ip = "141.136.1.1", alarmping = 200, alarmloss = 5, alarmjitter = 100 },
    { name = "Zayo", ip = "64.125.28.4", alarmping = 150, alarmloss = 3, alarmjitter = 75 },
    { name = "Windstream", ip = "208.42.224.1", alarmping = 200, alarmloss = 5, alarmjitter = 100 },
    { name = "Frontier", ip = "74.40.74.1", alarmping = 200, alarmloss = 5, alarmjitter = 100 }
  ]


# Alarm Threshold Guidelines:
# - alarmping: Milliseconds (typical ranges: 50-500ms)
# - alarmloss: Percentage (typical ranges: 1-20%)
# - alarmjitter: Milliseconds (typical ranges: 25-200ms)
# - alarmreceiver: Script path for custom alarm handling

# Network Distance Guidelines:
# - Local LAN: 1-10ms ping, 1% loss, 5-25ms jitter
# - Local WAN: 10-50ms ping, 1-2% loss, 10-50ms jitter  
# - Regional: 50-150ms ping, 2-5% loss, 25-100ms jitter
# - National: 100-300ms ping, 5-10% loss, 50-200ms jitter
# - International: 200-500ms ping, 5-20% loss, 100-300ms jitter

# Pro Tips:
# 1. Start with conservative thresholds and adjust based on actual performance
# 2. Use different alarm receivers for different severity levels
# 3. Group related services in the same organization
# 4. Include both IP addresses and DNS names for comprehensive monitoring
# 5. Monitor geographically diverse endpoints to detect regional issues
